# Generated by Django 4.1.1 on 2022-09-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=500)),
                ('expires_in', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=500)),
            ],
        ),
    ]
